// 全角色定义注册表
// 数据来源：characters-grid.png（8列4行，索引0-30，最后一格为空）
import type { Character, CharacterId } from '@/games/tragedy-looper/types';

export const ALL_CHARACTERS: Record<CharacterId, Character> = {
  // ========== 第1行（索引0-7）==========
  boy_student: {
    id: 'boy_student',
    name: '男学生',
    anxietyLimit: 2,
    initialLocation: 'school',
    forbiddenLocation: null,
    traits: ['student', 'boy'],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: null,
      description: '安慰同学',
      effect: '消除同一区域内除自身以外一名学生的1个不安标记',
    }],
  },
  girl_student: {
    id: 'girl_student',
    name: '女学生',
    anxietyLimit: 3,
    initialLocation: 'school',
    forbiddenLocation: null,
    traits: ['student', 'girl'],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: null,
      description: '安慰同学',
      effect: '消除同一区域内除自身以外一名学生的1个不安标记',
    }],
  },
  rich_man: {
    id: 'rich_man',
    name: '大小姐',
    anxietyLimit: 1,
    initialLocation: 'school',
    forbiddenLocation: null,
    traits: ['student', 'girl'],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: null,
      description: '贵族恩惠（限学校/都市）',
      effect: '【限学校或都市】在同一区域内的1名角色上放置1个友好标记',
    }],
  },
  shrine_maiden: {
    id: 'shrine_maiden',
    name: '巫女',
    anxietyLimit: 2,
    initialLocation: 'shrine',
    forbiddenLocation: 'city',
    traits: ['student', 'girl'],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: 1,
      description: '神社净化（限神社）',
      effect: '【限神社】移除神社的1个阴谋标记，并公开同一区域内1名角色的身份',
    }],
  },
  detective: {
    id: 'detective',
    name: '刑警',
    anxietyLimit: 3,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 4,
      maxUsesPerLoop: 1,
      description: '调查事件 + 守护',
      effect: '公开本轮回某一事件的私人信息；并在同一区域内的1名角色上放置1个守护标记',
    }],
  },
  office_worker: {
    id: 'office_worker',
    name: '上班族',
    anxietyLimit: 2,
    initialLocation: 'city',
    forbiddenLocation: 'school',
    traits: [],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: null,
      description: '坦白身份',
      effect: '剧作家必须公开该角色（上班族自身）的身份牌',
    }],
  },
  informer: {
    id: 'informer',
    name: '情报贩子',
    anxietyLimit: 3,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: ['girl'],
    abilities: [{
      goodwillRequired: 5,
      maxUsesPerLoop: 1,
      description: '情报交换',
      effect: '宣言一条支线的名称；剧作家必须公开本剧本正在使用的支线中，除所宣言支线之外的另一条支线',
    }],
  },
  doctor: {
    id: 'doctor',
    name: '医生',
    anxietyLimit: 2,
    initialLocation: 'hospital',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: null,
      description: '诊察',
      effect: '消除同一区域内1名角色的1个不安标记',
    }],
  },

  // ========== 第2行（索引8-15）==========
  patient: {
    id: 'patient',
    name: '入院患者',
    anxietyLimit: 2,
    initialLocation: 'hospital',
    forbiddenLocation: ['city', 'school', 'shrine'],
    traits: [],
    abilities: [],
  },
  class_rep: {
    id: 'class_rep',
    name: '班长',
    anxietyLimit: 2,
    initialLocation: 'school',
    forbiddenLocation: null,
    traits: ['student', 'girl'],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: 1,
      description: '带队移动（限学校）',
      effect: '【限学校】强制让同一区域内的1名角色随自身移动至下一区域',
    }],
  },
  factor: {
    id: 'factor',
    name: '意外因素',
    anxietyLimit: 3,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: ['student', 'boy'],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: null,
      description: '身份揭示',
      effect: '公开这个角色的身份（第二轮回起可用，不能被友好无视/绝对友好无视拒绝）',
    }],
  },
  alien: {
    id: 'alien',
    name: '异世界人',
    anxietyLimit: 2,
    initialLocation: 'shrine',
    forbiddenLocation: 'hospital',
    traits: ['girl'],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: 1,
      description: '危险感知',
      effect: '调查同一区域内是否存在身份为【杀手】或【杀人狂】的角色',
    }],
  },
  godly_being: {
    id: 'godly_being',
    name: '神格',
    anxietyLimit: 3,
    initialLocation: 'shrine',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 5,
      maxUsesPerLoop: 1,
      description: '事件揭露',
      effect: '公开一个事件的犯人',
    }],
  },
  idol: {
    id: 'idol',
    name: '偶像',
    anxietyLimit: 2,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: ['student', 'girl'],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: null,
      description: '偶像魅力',
      effect: '从自身以外同一区域的一名角色上移除1个不安标记；或在自身以外同一区域的一名角色上放置1个友好标记',
    }],
  },
  journalist: {
    id: 'journalist',
    name: '媒体记者',
    anxietyLimit: 2,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: null,
      description: '独家报道',
      effect: '在同一区域的一名角色上或者在所在的区域上放置1个阴谋标记',
    }],
  },
  boss: {
    id: 'boss',
    name: '大人物',
    anxietyLimit: 4,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 5,
      maxUsesPerLoop: 1,
      description: '领地情报',
      effect: '公开自身以外处于领地内的一名角色的身份',
    }],
  },

  // ========== 第3行（索引16-23）==========
  nurse: {
    id: 'nurse',
    name: '护士',
    anxietyLimit: 3,
    initialLocation: 'hospital',
    forbiddenLocation: null,
    traits: ['girl'],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: null,
      description: '专业护理',
      effect: '消除自身以外同一区域内1名角色的1个不安标记',
    }],
  },
  henchman: {
    id: 'henchman',
    name: '手下',
    anxietyLimit: 1,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 4,
      maxUsesPerLoop: null,
      description: '事件封印',
      effect: '本轮回中，此角色作为犯人的事件不会发生',
    }],
  },
  scientist: {
    id: 'scientist',
    name: '学者',
    anxietyLimit: 2,
    initialLocation: 'hospital',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: null,
      description: '实验重置',
      effect: '移除此角色上的所有标记；若使用了EX计量槽，将其增减1点',
    }],
  },
  illusion: {
    id: 'illusion',
    name: '幻想',
    anxietyLimit: 3,
    initialLocation: 'shrine',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: 1,
      description: '空间转移',
      effect: '令同一区域的一名角色移动到任意区域',
    }, {
      goodwillRequired: 5,
      maxUsesPerLoop: null,
      description: '消散',
      effect: '将此角色移出版图',
    }],
  },
  forensic: {
    id: 'forensic',
    name: '刑侦警察',
    anxietyLimit: 3,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: 1,
      description: '鉴识调查',
      effect: '在自身以外同一区域的两名角色间移动1个标记；或公开一具尸体的身份',
    }],
  },
  ai: {
    id: 'ai',
    name: 'A.I.',
    anxietyLimit: 4,
    initialLocation: 'hospital',
    forbiddenLocation: ['shrine', 'city', 'school'],
    traits: [],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: 1,
      description: '事件模拟',
      effect: '于公开情报中选择一个事件并结算，犯人视为A.I.；脚本家的决定改由领队进行（不视为发生了事件）',
    }],
  },
  teacher: {
    id: 'teacher',
    name: '教师',
    anxietyLimit: 2,
    initialLocation: 'school',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: 1,
      description: '关怀学生',
      effect: '消除同一区域内1名学生的1个不安标记；或公开同一区域内1名学生的身份',
    }],
  },
  transfer_student: {
    id: 'transfer_student',
    name: '转校生',
    anxietyLimit: 2,
    initialLocation: 'school',
    forbiddenLocation: null,
    traits: ['student', 'girl'],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: null,
      description: '净化标记',
      effect: '将同一区域内一名角色的1个阴谋标记替换为友好标记',
    }],
  },

  // ========== 第4行（索引24-30）==========
  soldier: {
    id: 'soldier',
    name: '军人',
    anxietyLimit: 3,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: 1,
      description: '精神压制',
      effect: '于同一区域的一名角色上放置2个不安标记；本轮回中主人公不会死亡',
    }],
  },
  black_cat: {
    id: 'black_cat',
    name: '黑猫',
    anxietyLimit: 0,
    initialLocation: 'shrine',
    forbiddenLocation: null,
    traits: [],
    abilities: [],
  },
  girl: {
    id: 'girl',
    name: '小女孩',
    anxietyLimit: 1,
    initialLocation: 'school',
    forbiddenLocation: ['hospital', 'city', 'shrine'],
    traits: ['girl', 'student'],
    abilities: [{
      goodwillRequired: 2,
      maxUsesPerLoop: null,
      description: '外出许可',
      effect: '本轮回中解除禁行限制，可移动到学校以外的区域',
    }, {
      goodwillRequired: 3,
      maxUsesPerLoop: 1,
      description: '冒险',
      effect: '移动到相邻区域',
    }],
  },
  cult_leader: {
    id: 'cult_leader',
    name: '教祖',
    anxietyLimit: 3,
    initialLocation: 'shrine',
    forbiddenLocation: null,
    traits: [],
    abilities: [{
      goodwillRequired: 5,
      maxUsesPerLoop: 1,
      description: '恐怖审判',
      effect: '公开自身以外不安标记达到不安临界值的一名角色的身份',
    }],
  },
  copycat: {
    id: 'copycat',
    name: '模仿者',
    anxietyLimit: 2,
    initialLocation: 'city',
    forbiddenLocation: null,
    traits: ['student', 'boy'],
    abilities: [{
      goodwillRequired: 3,
      maxUsesPerLoop: null,
      description: '身份揭示',
      effect: '公开与此角色相同身份的所有角色名字（第二轮回起可用，不能被友好无视/绝对友好无视拒绝）',
    }],
  },
  sacred_tree: {
    id: 'sacred_tree',
    name: '御神木',
    anxietyLimit: 4,
    initialLocation: 'shrine',
    forbiddenLocation: ['school', 'city', 'hospital'],
    traits: [],
    abilities: [],
  },
  little_sister: {
    id: 'little_sister',
    name: '妹妹',
    anxietyLimit: 3,
    initialLocation: 'shrine',
    forbiddenLocation: null,
    traits: ['girl'],
    abilities: [{
      goodwillRequired: 6,
      maxUsesPerLoop: null,
      description: '借用能力',
      effect: '借用同区域一名大人的友好能力（视为友好标记已满足），不能被友好无视/绝对友好无视拒绝，但受次数限制',
    }],
  },
};
